/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.Reservacion;
import Persistencia.pIniciodeSesion;
import Persistencia.pReservacion;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class frmReservacion extends javax.swing.JFrame {

    /**
     * Creates new form Reservacion
     */
    public frmReservacion() {
        initComponents();
        Cargardatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblTipodeHabitacion = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        txtFechadeReserva = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnVerEncargados = new javax.swing.JButton();
        lblFechadeReserva = new javax.swing.JLabel();
        lblHuespedes = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblPiso = new javax.swing.JLabel();
        txtHuespedes = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtPiso = new javax.swing.JTextField();
        txtTipodeHabitacion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResgistro = new javax.swing.JTable();
        btnVerEncargados1 = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jLabel3.setText("Reservación");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 110, 14);

        lblNumero.setText("Número:");
        getContentPane().add(lblNumero);
        lblNumero.setBounds(70, 50, 50, 23);

        lblTipodeHabitacion.setText("Tipo de Habitación:");
        getContentPane().add(lblTipodeHabitacion);
        lblTipodeHabitacion.setBounds(20, 90, 120, 23);

        lblEstado.setText("Estado:");
        getContentPane().add(lblEstado);
        lblEstado.setBounds(70, 290, 70, 23);

        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEstado);
        txtEstado.setBounds(130, 290, 88, 30);

        txtFechadeReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechadeReservaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFechadeReserva);
        txtFechadeReserva.setBounds(130, 130, 88, 30);

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumero);
        txtNumero.setBounds(130, 50, 88, 30);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(30, 350, 79, 23);

        btnVerEncargados.setText("Ver Reservaciones");
        btnVerEncargados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEncargadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerEncargados);
        btnVerEncargados.setBounds(350, 340, 150, 23);

        lblFechadeReserva.setText("Fecha de Reserva:");
        getContentPane().add(lblFechadeReserva);
        lblFechadeReserva.setBounds(20, 130, 120, 23);

        lblHuespedes.setText("Huéspedes:");
        getContentPane().add(lblHuespedes);
        lblHuespedes.setBounds(50, 170, 90, 23);

        lblPrecio.setText("Precio:");
        getContentPane().add(lblPrecio);
        lblPrecio.setBounds(70, 210, 60, 23);

        lblPiso.setText("Piso:");
        getContentPane().add(lblPiso);
        lblPiso.setBounds(80, 250, 90, 23);

        txtHuespedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHuespedesActionPerformed(evt);
            }
        });
        getContentPane().add(txtHuespedes);
        txtHuespedes.setBounds(130, 170, 88, 30);

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrecio);
        txtPrecio.setBounds(130, 210, 88, 30);

        txtPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPisoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPiso);
        txtPiso.setBounds(130, 250, 88, 30);

        txtTipodeHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipodeHabitacionActionPerformed(evt);
            }
        });
        getContentPane().add(txtTipodeHabitacion);
        txtTipodeHabitacion.setBounds(130, 90, 88, 30);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(230, 350, 80, 23);

        tblResgistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Número", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tblResgistro);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 50, 260, 260);

        btnVerEncargados1.setText("Ver Encargados");
        btnVerEncargados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEncargados1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerEncargados1);
        btnVerEncargados1.setBounds(350, 370, 150, 23);

        btnGuardar1.setText("Eliminar");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar1);
        btnGuardar1.setBounds(130, 350, 80, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtFechadeReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechadeReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechadeReservaActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVerEncargadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEncargadosActionPerformed
       VerReservaciones e = new VerReservaciones();
       this.hide();
       e.show();
    }//GEN-LAST:event_btnVerEncargadosActionPerformed

    private void txtHuespedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHuespedesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHuespedesActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPisoActionPerformed

    private void txtTipodeHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipodeHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipodeHabitacionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Reservacion R = new Reservacion();
        R.setNumero(this.txtNumero.getText());
        R.setTipodeHabitacion(this.txtTipodeHabitacion.getText());
        R.setFechadeReserva(this.txtFechadeReserva.getText());
        R.setHuespedes(this.txtHuespedes.getText());
        R.setPrecio(this.txtPrecio.getText());
        R.setPiso(this.txtPiso.getText());
        R.setEstado(this.txtEstado.getText());
        
          pReservacion cargar = new pReservacion();
              cargar.GuardarReservacion(R);
        Cargardatos();
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVerEncargados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEncargados1ActionPerformed
       Encargados e = new Encargados();
       this.hide();
       e.show();
    }//GEN-LAST:event_btnVerEncargados1ActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
       Reservacion r = new Reservacion();
   r.setNumero(tblResgistro.getModel().getValueAt(tblResgistro.getSelectedRow(),0).toString());
   pReservacion eliminar = new pReservacion();
   eliminar.BorrarReservacion(r);
   Cargardatos();
               
               
    }//GEN-LAST:event_btnGuardar1ActionPerformed

  public void Cargardatos(){
       pReservacion cargar = new pReservacion();
      List<Reservacion> lstReservaciones = new ArrayList<Reservacion>();
      lstReservaciones = cargar.Reservacion();
      
      DefaultTableModel dft=(DefaultTableModel) tblResgistro.getModel();
      
      dft.setRowCount(0);
      for(Reservacion r:lstReservaciones){
          dft.addRow(new Object[]{r.getNumero(),r.getPrecio()});
          
      }
      
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerEncargados;
    private javax.swing.JButton btnVerEncargados1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechadeReserva;
    private javax.swing.JLabel lblHuespedes;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPiso;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTipodeHabitacion;
    private javax.swing.JTable tblResgistro;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFechadeReserva;
    private javax.swing.JTextField txtHuespedes;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPiso;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTipodeHabitacion;
    // End of variables declaration//GEN-END:variables

    private void setNumero(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setTipodeHabitacion(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setFechadeReserva(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setEstado(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setPiso(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setHuespedes(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setPrecio(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
