/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.Reservacion;
import Persistencia.pReservacion;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class VerReservaciones extends javax.swing.JFrame {

    /**
     * Creates new form VerReservaciones
     */
    public VerReservaciones() {
        initComponents();
        Cargardatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVerReservacion = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 375));
        getContentPane().setLayout(null);

        tblVerReservacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Fecha de Reserva", "Tipo de Habitación", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tblVerReservacion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 440, 260);

        btnSalir.setText("Volver");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(190, 300, 79, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        frmReservacion r = new frmReservacion ();
           this.hide();
           r.show();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void Cargardatos(){
       pReservacion cargar = new pReservacion();
      List<Reservacion> lstVerReservaciones = new ArrayList<Reservacion>();
      lstVerReservaciones = cargar.Reservacion();
      
      DefaultTableModel dft=(DefaultTableModel) tblVerReservacion.getModel();
      
      dft.setRowCount(0);
      for(Reservacion r:lstVerReservaciones){
          dft.addRow(new Object[]{IniciodelUsuario.r.getNombre(), r.getFechadeReserva(), r.getTipodeHabitacion(), r.getPrecio()});
          
      }
      
  }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVerReservacion;
    // End of variables declaration//GEN-END:variables
}
